= Generating Docker artifacts in your Java project

:hp-tags: Java, Docker, Maven, Spotify

I have been working for 6 months in a new Java/Maven project in my company. It is quite exciting, we do a lot of cutting-edge technology and of course we use massively Jenkins for continous integration.

One of the problems that we started facing at one point is *what* to deliver. We were used to publish our WAR artifact to Artifactory, where it layed there to gain dust. Then our integration-test framework would run immediately after the build (triggered by `mvn integration-test`), and instead of retrieving the artifact, would use a new build run to generate the WAR in the target/ dir.

The test framework targets Amazon Web Services and from day1 we decided to have everything dockerized. So the deployment script would do the following:

. build the WAR file again
. copy it to the AWS target environment
. on AWS, pull the Jetty base image
. on AWS, package a new image
. on AWS, spawn the container (together together with other ancillary services)

This is clearly not very efficient. We have a lot of tools at our avaiablity (Artifactory in primis) but we are not able to make them work efficently.

So I took myself the task to improve our workflow, thanks also to our DevOps specialist who explained me a lot of nuts'n'bolts of Docker.

At one point it was clear that the best artifact to work with is not a WAR file, but a Docker image itself. I found out the wonderful *Docker-maven-plugin* by *Spotify* (check it out on https://github.com/spotify/docker-maven-plugin[their github repo]) to really suit my need. With it I can create and publish the Docker image of my app directly on Artifactory with a single Maven goal.

=== Prerequisites
Your Artifactory should have been enabled to run as a "Docker Registry". This basically means that we are able to push and pull images to and from it. 

The biggest example of a docker registry is the official https://hub.docker.com/[Docker Hub] where lots of mainstream porjects publish their public images.

Talk to your network administrator for all the concerns about it. You can also experiment by creating a Docker registry on your local machine while waiting for the IT guys to answer (it usally takes some time :P ). More informations on the Docker registry can be found in the Docker guides.

Second big point is, what kind of disk space on Artifactory do you have and what bandwidth availability. A well built Docker image should not require much more than a WAR/JAR artifact takes in terms of size and upload speed, but  this requires some tuning.

Long story short: the instruction order in your Dockerfile matters! Every line is a "layer" that Docker creates as basis for the next line, until you reach the end of the Dockerfile and the final image is done.

For my project, I use the official Jetty image from the Dockerhub onto which I then put my WAR, and produce a new image that I then upload to our private Artifactory.

This is what my Dockerfile *would* be:

-------------------
FROM jetty:9.3.12-jre8
COPY mywarfile.war /opt/jetty/webapps/
ENTRYPOINT ["java", "-jar", "/opt/jetty/start.jar"]
-------------------

You will see now how to produce the Docker image without needing any Dockerfile at all.

=== Configuration
Let's see how to configure the plugin in the project's `pom.xml`: 

[source, xml]
-------------------
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <version>0.4.13</version>
  <configuration>
    <imageTags>
      <imageTag>${project.version}-${myimage.build}</imageTag>
    </imageTags>
    <imageName>artifactory.mycompany.net/applications/myapp</imageName>
    <baseImage>jetty:9.3.12-jre8</baseImage>
    <entryPoint>["java", "-jar", "/opt/jetty/start.jar"]</entryPoint>
    <workdir>/opt/jetty</workdir>
    <exposes>8080</exposes>
    <resources>
      <resource>
        <targetPath>/opt/jetty/webapps/</targetPath>
        <directory>${project.build.directory}</directory>
        <include>${project.build.finalName}.war</include>
      </resource>
    </resources>
    <serverId>server_entry</serverId>
    <registryUrl>https://artifactory.mycompany.net</registryUrl>
  </configuration>
</plugin>
-------------------

As you can see the parameters resemble pretty much the intended Dockerfile.

Notice that the *server_entry* is the label of an entry that you have to insert into your local `~/.m2/settings.xml` as such:

[source, xml]
-------------------
<server>
  <id>server_entry</id>
  <username>insert_login_name_here</username>
  <password>insert_password_here</password>
  <configuration>
    <email>insert_your_email_here</email>
  </configuration>
</server>
-------------------

Strangely enough the email field is *mandatory* for the current version of the spotify Docker-maven-plugin to work correctly, so watch out!

=== Usage
You can see that what I put in the pom.xml is parametrized by some automatic Maven variables (they look like `${something}`).
There is a residual parameter which is `${myimage.build}` which in my case does not come from Maven internals, but from the command line: you can run the docker image generation like this:

-------------------
mvn docker:build -Dmyimage.build=12345
-------------------

and this will result in a Docker image created locally with tag

-------------------
artifactory.mycompany.net/applications/myapp:0.0.1-SNAPSHOT-12345
-------------------

(You can check this out with `docker ps -a command`). The `0.0.1-SNAPSHOT` part here simply comes from the version of your project (on top of your `pom.xml` file), so it can be totally different in your case, of course.

To push this image to artifactory, we simply need to add a push command to the command line:

-------------------
mvn docker:build -Dmyimage.build=12345 -DpushImage
-------------------

That's it. 

If you use Jenkins CI like in my case, it is easy to inject the ${myimage.build} value from the Jenkins built-in variable BUILD_NUMBER, so every successful job run will automatically push a different image version on Artifactory. Or you could just forget about it and remove the versioning entirely, and only use the "latest" tag (this is automatically managed by the Docker-maven-plugin again): your choice :)

Have fun!
